const colors = {
  light: {
    text: "#edf0f7",
    tint: "#8B52FF",
    background: "#060c1b",
    foreground: "#edf0f7",
    card: "#090e20",
    cardForeground: "#edf0f7",
    primary: "#8B52FF",
    primaryForeground: "#ffffff",
    secondary: "#07B5D1",
    secondaryForeground: "#ffffff",
    muted: "#1d2540",
    mutedForeground: "#8a9cc0",
    accent: "#D42EA0",
    accentForeground: "#ffffff",
    destructive: "#f04040",
    destructiveForeground: "#ffffff",
    border: "#1d2540",
    input: "#1d2540",
  },
  dark: {
    text: "#edf0f7",
    tint: "#8B52FF",
    background: "#060c1b",
    foreground: "#edf0f7",
    card: "#090e20",
    cardForeground: "#edf0f7",
    primary: "#8B52FF",
    primaryForeground: "#ffffff",
    secondary: "#07B5D1",
    secondaryForeground: "#ffffff",
    muted: "#1d2540",
    mutedForeground: "#8a9cc0",
    accent: "#D42EA0",
    accentForeground: "#ffffff",
    destructive: "#f04040",
    destructiveForeground: "#ffffff",
    border: "#1d2540",
    input: "#1d2540",
  },
  radius: 12,
};

export default colors;
